### ISSUE TITLE
Compiling docopt with gdc

### ISSUE THREAD

**Issue by grogancolin** [docopt/docopt.d#3]
I have docopt as a dependancy on one of my projects, when compiling via gdc, this is the output:

```
 $ dub build --compiler=gdc
Building docopt 0.6.1-b.2 configuration "library", build type debug.
Running gdc...
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:59: error: std.algorithm.indexOf!("a == b", string, string).indexOf at /usr/include/d/4.8/std/algorithm.d:4828 conflicts with std.string.indexOf!(char, char).indexOf at /usr/include/d/4.8/std/string.d:412
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:59: error: function std.algorithm.indexOf!("a == b", string, string).indexOf is deprecated - Please use std.algorithm.countUntil instead.
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:84: error: std.algorithm.indexOf!("a == b", string, string).indexOf at /usr/include/d/4.8/std/algorithm.d:4828 conflicts with std.string.indexOf!(char, char).indexOf at /usr/include/d/4.8/std/string.d:412
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:84: error: function std.algorithm.indexOf!("a == b", string, string).indexOf is deprecated - Please use std.algorithm.countUntil instead.
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:264: error: no property 'among' for type 'string'
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:309: error: no property 'among' for type 'string'
../../.dub/packages/docopt-0.6.1-b.2/source/docopt.d:508: error: no property 'toPrettyString' for type 'JSONValue'
cc1d: all warnings being treated as errors
```

Some are deprecation warnings so should be easy fix.
Haven't investigated the others in-depth yet...

Compiling with:
```
$ gdc --version
gdc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by rwtolbert** [comment]
Thanks for the pointers.

I'll admit that I haven't used gdc/ldc so this gives me a good reason to get those installed and get this fixed.

Good to know someone is using this besides me.

**Comment by rwtolbert** [comment]
ok, I've updated to 0.6.1-b.3

this also spurred me to add more of the tests to unittest so dub test always runs them

tests pass with 

	> dmd --version                                                               
	DMD64 D Compiler v2.067.1
	
	> gdc --version
	gdc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
	
	> ldc2 --version 
	LDC - the LLVM D compiler (0.15.2-beta1):
	  based on DMD v2.066.1 and LLVM 3.6.0
	  Default target: x86_64-unknown-linux-gnu
	  Host CPU: corei7
	  http://dlang.org - http://wiki.dlang.org/LDC
	
	  Registered Targets:
	    x86    - 32-bit X86: Pentium-Pro and above
	    x86-64 - 64-bit X86: EM64T and AMD64

**Comment by grogancolin** [comment]
Excellent. I'll update this eve and test it out.
Thanks!
