### ISSUE TITLE
Run tests on CI.

### ISSUE THREAD

**Issue by kubo39** [docopt/docopt.d#8]
This is question: Do you have any plans for using CI service like travis? :)

**Comment by rwtolbert** [comment]
I would love to do that. Just haven't ever set it up for a D project before.

thanks for the hint and if I have trouble getting it working, i'll let you know.

**Comment by kubo39** [comment]
Thanks for the reply.
 I've done regression test at #7 by [the config](https://github.com/kubo39/docopt.d/commit/2dc6d060d37c56a0d0665d2930ca03eaf98db462).
I send pull request this branch(travis I named) if you hope :)
